### ISSUE TITLE
Can I use it for static HTML/CSS Prototyping?

### ISSUE THREAD

**Issue by jitendravyas** [jxnblk/ejsx#1]
If yes, How I can extend a template?

I work on a project where I convert Sketch file to HTML/CSS and later a React dev will use my code to convert into React. I currently use raw HTML but I think know I can use ejsx to produce HTML while will save time for react developer to use my code, am i right?

**Comment by jxnblk** [comment]
You _could_ use this for prototyping, and it's definitely intended for that.

As for sharing anything with a react developer, I'd ask them about their preferences. It might be worth using React itself if you're up for it.

**Comment by jxnblk** [comment]
As for "extending" a template, React does not work the way some other templating languages do. Instead you would just nest things declaratively like in HTML. For example you could have an Html component that has a PageLayout component inside of it. See https://github.com/jxnblk/ejsx/blob/master/docs/Root.jsx for an example of how the docs for this repo are structured.

**Comment by jitendravyas** [comment]
I don't know React and vanilla JS much. I was thinking if by using ejsx I can help more to react devs compare to just giving them plain HTML.
