### ISSUE TITLE
Error: Couldn't find preset "react" relative to directory "/Users/jitendravyas/my-projects/ejsx

### ISSUE THREAD

**Issue by jitendravyas** [jxnblk/ejsx#2]
`Node -v 6.7.0`

I'm following docs and getting this error 

![image](https://cloud.githubusercontent.com/assets/77309/19624263/d33f2da2-990a-11e6-9584-31482f52cedf.png)

Root.jsx

```
<html>
  <h1>Hello</h1>
</html>

```

Header.jsx

```
<header>
  <h1>{props.title}</h1>
</header>

```

**Comment by colmtuite** [comment]
You need to install React and a bunch of other dependencies.

`"babel-core": "^6.17.0",  
    "babel-preset-react": "^6.16.0",  
    "meow": "^3.7.0",  
    "react": "^15.3.2",  
    "react-dom": "^15.3.2"`

**Comment by jitendravyas** [comment]
oh ok. I didn't know that. This info should have been included on the Docs then. Is there a single command to install all of them?

**Comment by colmtuite** [comment]
Just add them to your devDependencies in your package.json and run `npm install`

**Comment by jitendravyas** [comment]
@colmtuite I don't have any package.json. Do I need to create new one and adds all these?

**Comment by jxnblk** [comment]
Ah sorry. Will add more details to the readme

**Comment by jxnblk** [comment]
@jitendravyas did you install ejsx with `npm install -g ejsx`? (Note the -g flag)

**Comment by jitendravyas** [comment]
@jxnblk Yes with -g flag. Do you mean ejsx install should have automatically installed automatically

`"babel-core": "^6.17.0", "babel-preset-react": "^6.16.0", "meow": "^3.7.0", "react": "^15.3.2", "react-dom": "^15.3.2"`

**Comment by jxnblk** [comment]
It should have, but maybe something specific to your setup is different than mine.

To get around this for now, you can try:
- run `npm init` in your project folder
- run `npm install --save ejsx`

Then try running again to see if it works

**Comment by jitendravyas** [comment]
after `npm init` when I ran `npm install --save ejsx`

`npm ERR! Refusing to install ejsx as a dependency of itself`

**Comment by jxnblk** [comment]
Ah. You named the project folder the same as the module. Try changing the name in your package.json to something else

**Comment by jxnblk** [comment]
I would maybe try renaming the folder as well and seeing if the global script works then

**Comment by jitendravyas** [comment]
1. I get this message everytime and I need to  delete index.html everytime `zsh: file exists: index.html`
2. `npm install --save ejsx` went fine now but now i get this error when i run
   `ejsx components > index.html`

```
evalmachine.<anonymous>:14
    React.createElement(Root, props)
                        ^
ReferenceError: Root is not defined
```

**Comment by jxnblk** [comment]
For 1, I think that's a zsh thing, you can try `ejsx components >! index.html` or removing the `index.html` file before running.

For 2, do you have a file named `Root.jsx` in the components folder?

**Comment by jitendravyas** [comment]
1. This is working I think `ejsx components >! index.html`
2. Now i get index.html with this content 
   `<!DOCTYPE html><html><h1>Hello</h1></html>`
   And getting this warning
   `Warning: validateDOMNesting(...): <h1> cannot appear as a child of <html>. See Root > html > h1.`

**Comment by jxnblk** [comment]
Yeah, that's just a general React warning that you can safely ignore. React doesn't like omitting the optional `head` and `body` tags.
