### ISSUE TITLE
Is it possible to pass a string of classes?

### ISSUE THREAD

**Issue by colmtuite** [jxnblk/ejsx#3]
I want to do something like this...

```
const sharedClasses = {
    'bc-pink',
    'color-black',
    'padding-m',
    'mb-l'
};

<a
    className="{sharedClasses}"
    href={props.url}
    data-id={props.id}>
    {props.text}
</a>
```

**Comment by jxnblk** [comment]
Any reason you couldn't pass these through as props? As it currently works, you can't use JS like this, and each jsx file must be wrapped with a single element.
